# html lang
language: zh

# main menu navigation
menu:
  Home: /
  Archives: /archives
  Tags: /tags
  Categories: /categories

# Miscelaneous
favicon: /favicon.ico

# highlight
highlight_theme: default

# fireworks
fireworks: false

# stylesheets loaded in the <head>
stylesheets:
- /css/index.css

# scripts loaded in the end of the body
scripts:
- /js/utils.js
- /js/fancybox.js
- /js/sidebar.js
- /js/copy.js
- /js/fireworks.js
- /js/transition.js
- /js/scroll.js
- /js/head.js

cdn:
  css:
    fontawesome: https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.min.css
  js:
    anime: /js/third-party/anime.min.js
    jquery: /js/third-party/jquery.min.js
    fancybox: /js/third-party/jquery.fancybox.min.js
    velocity: /js/third-party/velocity.min.js 
    velocity-ui: /js/third-party/velocity.ui.min.js 

# Post info settings

avatar: https://ws1.sinaimg.cn/large/8700af19ly1fj3cdqu3f6j20ix0iwq5r.jpg

top_img: true 

social:
  github: https://github.com/Molunerfinn
  weibo: http://weibo.com/mybluedreams/
  rss: https://molunerfinn.com/atom.xml 

post_meta:
  date_type: updated # created or updated 
  categories: true
  tags: true

toc:
  enable: true

addThis:
  enable: true
  pubid: ra-5994f8f0fea9a5f4

disqus:
  enable: true
  shortname: molunerfinn
  count: true


since: 2013

ICP:
  enable: false
  text: 
  url: 

# Sidebar Settings

# Links
links_title: Links
links:
  Molunerfinn: https://molunerfinn.com
  PiEgg: https://piegg.cn
  Elody: https://elody-07.github.io

# Version
version: 1.0